apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: {{ .Values.payments.replicas }}
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: {{ .Values.payments.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: PAYMENT_FAILURE_RATE
          value: "{{ .Values.payments.failureRate }}"
        - name: PAYMENT_LATENCY_MS
          value: "{{ .Values.payments.latencyMs }}"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: payments